import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export const SUPPORTED_LANGUAGES = [
  ['ar', 'العربية', 'SA'], ['zh', '中文', 'CN'], ['nl', 'Nederlands', 'NL'], ['en', 'English', 'GB'],
  ['fr', 'Français', 'FR'], ['de', 'Deutsch', 'DE'], ['ha', 'Hausa', 'NG'], ['hi', 'हिन्दी', 'IN'],
  ['ig', 'Igbo', 'NG'], ['id', 'Bahasa Indonesia', 'ID'], ['it', 'Italiano', 'IT'], ['ja', '日本語', 'JP'],
  ['ko', '한국어', 'KR'], ['ms', 'Bahasa Melayu', 'MY'], ['pt', 'Português', 'PT'], ['ru', 'Русский', 'RU'],
  ['es', 'Español', 'ES'], ['sw', 'Kiswahili', 'KE'], ['th', 'ไทย', 'TH'], ['tr', 'Türkçe', 'TR'], ['ur', 'اردو', 'PK'],
] as const;

export type LanguageCode = typeof SUPPORTED_LANGUAGES[number][0];
type Dictionary = Record<string, string>;

const en: Dictionary = {
  numberMerge: 'NUMBER MERGE', player: 'Player', level: 'Level {level}', stage: 'STAGE 1',
  rewards: 'Rewards', shop: 'Shop', home: 'Home', play: 'Play', profile: 'Profile',
  welcomeBack: 'Welcome back,', dailyReward: 'Daily Reward', claimFree: 'Claim your free reward!', claim: 'CLAIM',
  highestBlock: 'HIGHEST BLOCK', keepMerging: 'Keep merging. Reach {goal} next.', nextGoal: 'Next Goal:',
  classicMerge: 'Classic Merge', goalReach: 'Goal: Reach', bestScore: 'BEST SCORE', playNow: 'PLAY NOW',
  account: 'ACCOUNT', playerProfile: 'Player Profile', username: 'Username', enterName: 'Enter your name',
  country: 'Country', language: 'Language', searchCountries: 'Search countries', searchLanguages: 'Search languages',
  noCountry: 'No country found', chooseYour: 'CHOOSE YOUR', gameAvatar: 'Game Avatar', styles: '{count} styles',
  saveProfile: 'Save Profile', cancel: 'Cancel', backHome: 'Back to home', openProfile: 'Open player profile',
  chooseAvatar: 'Choose {name} avatar', gems: 'GEMS', score: 'SCORE', best: 'BEST', goal: 'GOAL',
  next: 'NEXT', smash: 'Smash', swap: 'Swap', undo: 'Undo', combo: 'COMBO', tapSmash: 'Tap a block to smash it',
  pause: 'Pause', shootColumn: 'Shoot into column {column}', nextBlock: 'Next block: {value}', getGems: 'Get gems',
  getMoreGems: 'Get more gems', mainNavigation: 'Main navigation', progressNext: '{progress}% progress to next level',
  currentMilestone: 'Current milestone', block: '{value} block', comingSoon: 'Coming soon', dailySoon: 'Daily rewards are coming soon', gemSoon: 'Gem shop coming soon',
  tutorial1Title: 'Tap to Shoot!', tutorial1Body: 'Send the block up the glowing lane', tutorial2Title: 'Well Done!', tutorial2Body: 'Now merge the same numbers',
  tutorial3Title: 'Shoot it!', tutorial3Body: 'Two matching blocks make a higher number', tutorial4Title: 'Awesome!', tutorial4Body: 'You’re ready to play', skipTutorial: 'Skip tutorial',
  firstMission: 'YOUR FIRST MISSION', firstGoal: 'First Goal', createFirst: 'Create a 256 block to reach your first milestone.', letsPlay: 'Let’s play',
  takeBreath: 'TAKE A BREATH', paused: 'Paused', resume: 'Resume', restartGame: 'Restart game', noMoves: 'NO MORE MOVES', gameOver: 'Game Over', playAgain: 'Play again',
  newMilestone: 'NEW MILESTONE', newBlockUnlocked: 'New Block Unlocked!', yourReward: 'YOUR REWARD', claimDouble: 'Claim ×2', noThanks: 'No thanks',
  progressionMilestone: 'PROGRESSION MILESTONE', reached: '{value} Reached!', blockRetired: 'BLOCK RETIRED', noLongerAppear: '{value} will no longer appear', nextMilestone: 'NEXT MILESTONE', continue: 'Continue',
  rareMerge: 'RARE MERGE', createdAgain: 'Created Again!', createdAgainBody: '{value} created again. Double it?',
};

const packs: Record<Exclude<LanguageCode, 'en'>, Dictionary> = {
  ar: { player:'اللاعب',level:'المستوى {level}',stage:'المرحلة 1',rewards:'المكافآت',shop:'المتجر',home:'الرئيسية',play:'العب',profile:'الملف الشخصي',welcomeBack:'مرحبًا بعودتك،',dailyReward:'المكافأة اليومية',claimFree:'احصل على مكافأتك المجانية!',claim:'استلام',highestBlock:'أعلى كتلة',keepMerging:'واصل الدمج. الهدف التالي {goal}.',nextGoal:'الهدف التالي:',classicMerge:'الدمج الكلاسيكي',goalReach:'الهدف: الوصول إلى',bestScore:'أفضل نتيجة',playNow:'العب الآن',account:'الحساب',playerProfile:'ملف اللاعب',username:'اسم المستخدم',enterName:'أدخل اسمك',country:'الدولة',language:'اللغة',searchCountries:'ابحث عن دولة',searchLanguages:'ابحث عن لغة',noCountry:'لم يتم العثور على دولة',chooseYour:'اختر',gameAvatar:'شخصية اللعبة',styles:'{count} أنماط',saveProfile:'حفظ الملف',cancel:'إلغاء',gems:'الجواهر',score:'النتيجة',best:'الأفضل',goal:'الهدف',next:'التالي',smash:'تحطيم',swap:'تبديل',undo:'تراجع',pause:'إيقاف مؤقت',continue:'متابعة',noThanks:'لا شكرًا',backHome:'العودة للرئيسية',gameOver:'انتهت اللعبة',playAgain:'العب مجددًا',paused:'متوقفة',resume:'استئناف',restartGame:'إعادة اللعبة',comingSoon:'قريبًا' },
  zh: { player:'玩家',level:'等级 {level}',stage:'第 1 关',rewards:'奖励',shop:'商店',home:'主页',play:'开始',profile:'个人资料',welcomeBack:'欢迎回来，',dailyReward:'每日奖励',claimFree:'领取免费奖励！',claim:'领取',highestBlock:'最高方块',keepMerging:'继续合并，下一个目标 {goal}。',nextGoal:'下一个目标：',classicMerge:'经典合并',goalReach:'目标：达到',bestScore:'最高分',playNow:'立即游戏',account:'账户',playerProfile:'玩家资料',username:'用户名',enterName:'输入名字',country:'国家',language:'语言',searchCountries:'搜索国家',searchLanguages:'搜索语言',noCountry:'未找到国家',chooseYour:'选择你的',gameAvatar:'游戏头像',styles:'{count} 种样式',saveProfile:'保存资料',cancel:'取消',gems:'宝石',score:'分数',best:'最佳',goal:'目标',next:'下一个',smash:'粉碎',swap:'交换',undo:'撤销',pause:'暂停',continue:'继续',noThanks:'不用了',backHome:'返回主页',gameOver:'游戏结束',playAgain:'再玩一次',paused:'已暂停',resume:'继续',restartGame:'重新开始',comingSoon:'即将推出' },
  nl: { player:'Speler',level:'Niveau {level}',stage:'FASE 1',rewards:'Beloningen',shop:'Winkel',home:'Home',play:'Spelen',profile:'Profiel',welcomeBack:'Welkom terug,',dailyReward:'Dagelijkse beloning',claimFree:'Claim je gratis beloning!',claim:'CLAIM',highestBlock:'HOOGSTE BLOK',keepMerging:'Blijf samenvoegen. Bereik hierna {goal}.',nextGoal:'Volgend doel:',classicMerge:'Klassiek samenvoegen',goalReach:'Doel: bereik',bestScore:'BESTE SCORE',playNow:'SPEEL NU',account:'ACCOUNT',playerProfile:'Spelersprofiel',username:'Gebruikersnaam',enterName:'Vul je naam in',country:'Land',language:'Taal',searchCountries:'Landen zoeken',searchLanguages:'Talen zoeken',noCountry:'Geen land gevonden',chooseYour:'KIES JE',gameAvatar:'Game-avatar',styles:'{count} stijlen',saveProfile:'Profiel opslaan',cancel:'Annuleren',gems:'EDELSTENEN',score:'SCORE',best:'BESTE',goal:'DOEL',next:'VOLGENDE',smash:'Slaan',swap:'Wisselen',undo:'Ongedaan',pause:'Pauze',continue:'Doorgaan',noThanks:'Nee bedankt',backHome:'Terug naar home',gameOver:'Game over',playAgain:'Opnieuw spelen',paused:'Gepauzeerd',resume:'Hervatten',restartGame:'Spel herstarten',comingSoon:'Binnenkort' },
  fr: { player:'Joueur',level:'Niveau {level}',stage:'NIVEAU 1',rewards:'Récompenses',shop:'Boutique',home:'Accueil',play:'Jouer',profile:'Profil',welcomeBack:'Bon retour,',dailyReward:'Récompense quotidienne',claimFree:'Récupérez votre récompense gratuite !',claim:'RÉCUPÉRER',highestBlock:'BLOC LE PLUS ÉLEVÉ',keepMerging:'Continuez à fusionner. Atteignez {goal}.',nextGoal:'Prochain objectif :',classicMerge:'Fusion classique',goalReach:'Objectif : atteindre',bestScore:'MEILLEUR SCORE',playNow:'JOUER',account:'COMPTE',playerProfile:'Profil du joueur',username:"Nom d’utilisateur",enterName:'Entrez votre nom',country:'Pays',language:'Langue',searchCountries:'Rechercher un pays',searchLanguages:'Rechercher une langue',noCountry:'Aucun pays trouvé',chooseYour:'CHOISISSEZ VOTRE',gameAvatar:'Avatar de jeu',styles:'{count} styles',saveProfile:'Enregistrer',cancel:'Annuler',gems:'GEMMES',score:'SCORE',best:'MEILLEUR',goal:'OBJECTIF',next:'SUIVANT',smash:'Frapper',swap:'Échanger',undo:'Annuler',pause:'Pause',continue:'Continuer',noThanks:'Non merci',backHome:"Retour à l’accueil",gameOver:'Partie terminée',playAgain:'Rejouer',paused:'En pause',resume:'Reprendre',restartGame:'Recommencer',comingSoon:'Bientôt disponible' },
  de: { player:'Spieler',level:'Level {level}',stage:'STUFE 1',rewards:'Belohnungen',shop:'Shop',home:'Start',play:'Spielen',profile:'Profil',welcomeBack:'Willkommen zurück,',dailyReward:'Tägliche Belohnung',claimFree:'Hol dir deine kostenlose Belohnung!',claim:'ABHOLEN',highestBlock:'HÖCHSTER BLOCK',keepMerging:'Weiter kombinieren. Erreiche {goal}.',nextGoal:'Nächstes Ziel:',classicMerge:'Klassisches Kombinieren',goalReach:'Ziel: Erreiche',bestScore:'BESTPUNKTZAHL',playNow:'JETZT SPIELEN',account:'KONTO',playerProfile:'Spielerprofil',username:'Benutzername',enterName:'Namen eingeben',country:'Land',language:'Sprache',searchCountries:'Länder suchen',searchLanguages:'Sprachen suchen',noCountry:'Kein Land gefunden',chooseYour:'WÄHLE DEINEN',gameAvatar:'Spielavatar',styles:'{count} Stile',saveProfile:'Profil speichern',cancel:'Abbrechen',gems:'JUWELEN',score:'PUNKTE',best:'BESTE',goal:'ZIEL',next:'NÄCHSTER',smash:'Zerschlagen',swap:'Tauschen',undo:'Rückgängig',pause:'Pause',continue:'Weiter',noThanks:'Nein danke',backHome:'Zurück zum Start',gameOver:'Spiel vorbei',playAgain:'Nochmal spielen',paused:'Pausiert',resume:'Fortsetzen',restartGame:'Neu starten',comingSoon:'Demnächst' },
  ha: { player:'Ɗan wasa',level:'Mataki {level}',stage:'MATAKI 1',rewards:'Lada',shop:'Shago',home:'Gida',play:'Kunna',profile:'Bayani',welcomeBack:'Barka da dawowa,',dailyReward:'Ladar yau',claimFree:'Karɓi ladarka ta kyauta!',claim:'KARƁA',highestBlock:'BULO MAFI GIRMA',keepMerging:'Ci gaba da haɗawa. Kai {goal}.',nextGoal:'Buri na gaba:',classicMerge:'Haɗawa na gargajiya',goalReach:'Buri: Kai',bestScore:'MAFI KYAU',playNow:'KUNNA YANZU',account:'ASUSU',playerProfile:'Bayanin ɗan wasa',username:'Sunan mai amfani',enterName:'Shigar da suna',country:'Ƙasa',language:'Harshe',searchCountries:'Nemo ƙasa',searchLanguages:'Nemo harshe',noCountry:'Ba a sami ƙasa ba',chooseYour:'ZAƁI',gameAvatar:'Hoton wasa',styles:'Salo {count}',saveProfile:'Ajiye bayani',cancel:'Soke',gems:'DUWATSU',score:'MAKI',best:'MAFI KYAU',goal:'BURI',next:'NA GABA',smash:'Fasa',swap:'Musanya',undo:'Mayar',pause:'Dakatar',continue:'Ci gaba',noThanks:'A’a, na gode',backHome:'Koma gida',gameOver:'Wasa ya ƙare',playAgain:'Sake kunnawa',paused:'An dakatar',resume:'Ci gaba',restartGame:'Sake fara wasa',comingSoon:'Yana nan tafe' },
  hi: { player:'खिलाड़ी',level:'स्तर {level}',stage:'चरण 1',rewards:'पुरस्कार',shop:'दुकान',home:'होम',play:'खेलें',profile:'प्रोफ़ाइल',welcomeBack:'वापसी पर स्वागत है,',dailyReward:'दैनिक पुरस्कार',claimFree:'अपना मुफ़्त पुरस्कार लें!',claim:'प्राप्त करें',highestBlock:'सबसे बड़ा ब्लॉक',keepMerging:'मर्ज करते रहें। अगला लक्ष्य {goal}।',nextGoal:'अगला लक्ष्य:',classicMerge:'क्लासिक मर्ज',goalReach:'लक्ष्य: पहुँचें',bestScore:'सर्वश्रेष्ठ स्कोर',playNow:'अभी खेलें',account:'खाता',playerProfile:'खिलाड़ी प्रोफ़ाइल',username:'यूज़रनेम',enterName:'अपना नाम लिखें',country:'देश',language:'भाषा',searchCountries:'देश खोजें',searchLanguages:'भाषा खोजें',noCountry:'देश नहीं मिला',chooseYour:'चुनें',gameAvatar:'गेम अवतार',styles:'{count} शैलियाँ',saveProfile:'प्रोफ़ाइल सहेजें',cancel:'रद्द करें',gems:'रत्न',score:'स्कोर',best:'सर्वश्रेष्ठ',goal:'लक्ष्य',next:'अगला',smash:'तोड़ें',swap:'बदलें',undo:'वापस',pause:'रोकें',continue:'जारी रखें',noThanks:'नहीं धन्यवाद',backHome:'होम पर वापस',gameOver:'खेल समाप्त',playAgain:'फिर खेलें',paused:'रुका हुआ',resume:'जारी रखें',restartGame:'खेल फिर शुरू करें',comingSoon:'जल्द आ रहा है' },
  ig: { player:'Onye egwuregwu',level:'Ọkwa {level}',stage:'ỌKWA 1',rewards:'Ụgwọ',shop:'Ụlọ ahịa',home:'Ụlọ',play:'Gwuo',profile:'Profaịlụ',welcomeBack:'Nnọọ ọzọ,',dailyReward:'Ụgwọ kwa ụbọchị',claimFree:'Nara ụgwọ efu gị!',claim:'NARA',highestBlock:'NGWỤCHA KACHA ELU',keepMerging:'Gaa n’ihu ijikọta. Ruo {goal}.',nextGoal:'Ebumnuche ọzọ:',classicMerge:'Njikọ oge ochie',goalReach:'Ebumnuche: Ruo',bestScore:'AKARA KACHA MMA',playNow:'GWUO UGBUA',account:'AKAỤNTỤ',playerProfile:'Profaịlụ onye egwuregwu',username:'Aha njirimara',enterName:'Tinye aha gị',country:'Mba',language:'Asụsụ',searchCountries:'Chọọ mba',searchLanguages:'Chọọ asụsụ',noCountry:'Ahụghị mba',chooseYour:'HỌRỌ',gameAvatar:'Avatar egwuregwu',styles:'Ụdị {count}',saveProfile:'Chekwaa profaịlụ',cancel:'Kagbuo',gems:'ỌLA',score:'AKARA',best:'KACHA MMA',goal:'EBUMNUCHE',next:'ỌZỌ',smash:'Kụwaa',swap:'Gbanwee',undo:'Weghachi',pause:'Kwụsị',continue:'Gaa n’ihu',noThanks:'Mba, daalụ',backHome:'Laghachi ụlọ',gameOver:'Egwuregwu agwụla',playAgain:'Gwuo ọzọ',paused:'Akwụsịla',resume:'Gaa n’ihu',restartGame:'Malite ọzọ',comingSoon:'Na-abịa n’oge adịghị anya' },
  id: { player:'Pemain',level:'Level {level}',stage:'TAHAP 1',rewards:'Hadiah',shop:'Toko',home:'Beranda',play:'Main',profile:'Profil',welcomeBack:'Selamat datang kembali,',dailyReward:'Hadiah Harian',claimFree:'Klaim hadiah gratismu!',claim:'KLAIM',highestBlock:'BLOK TERTINGGI',keepMerging:'Terus gabungkan. Capai {goal}.',nextGoal:'Target Berikutnya:',classicMerge:'Gabung Klasik',goalReach:'Target: Capai',bestScore:'SKOR TERBAIK',playNow:'MAIN SEKARANG',account:'AKUN',playerProfile:'Profil Pemain',username:'Nama pengguna',enterName:'Masukkan namamu',country:'Negara',language:'Bahasa',searchCountries:'Cari negara',searchLanguages:'Cari bahasa',noCountry:'Negara tidak ditemukan',chooseYour:'PILIH',gameAvatar:'Avatar Game',styles:'{count} gaya',saveProfile:'Simpan Profil',cancel:'Batal',gems:'PERMATA',score:'SKOR',best:'TERBAIK',goal:'TARGET',next:'BERIKUTNYA',smash:'Hancurkan',swap:'Tukar',undo:'Urungkan',pause:'Jeda',continue:'Lanjut',noThanks:'Tidak, terima kasih',backHome:'Kembali ke beranda',gameOver:'Game Selesai',playAgain:'Main lagi',paused:'Dijeda',resume:'Lanjutkan',restartGame:'Mulai ulang',comingSoon:'Segera hadir' },
  it: { player:'Giocatore',level:'Livello {level}',stage:'LIVELLO 1',rewards:'Premi',shop:'Negozio',home:'Home',play:'Gioca',profile:'Profilo',welcomeBack:'Bentornato,',dailyReward:'Premio giornaliero',claimFree:'Ritira il premio gratuito!',claim:'RITIRA',highestBlock:'BLOCCO PIÙ ALTO',keepMerging:'Continua a unire. Raggiungi {goal}.',nextGoal:'Prossimo obiettivo:',classicMerge:'Unione classica',goalReach:'Obiettivo: raggiungi',bestScore:'MIGLIOR PUNTEGGIO',playNow:'GIOCA ORA',account:'ACCOUNT',playerProfile:'Profilo giocatore',username:'Nome utente',enterName:'Inserisci il tuo nome',country:'Paese',language:'Lingua',searchCountries:'Cerca paesi',searchLanguages:'Cerca lingue',noCountry:'Nessun paese trovato',chooseYour:'SCEGLI IL TUO',gameAvatar:'Avatar di gioco',styles:'{count} stili',saveProfile:'Salva profilo',cancel:'Annulla',gems:'GEMME',score:'PUNTEGGIO',best:'MIGLIORE',goal:'OBIETTIVO',next:'PROSSIMO',smash:'Distruggi',swap:'Scambia',undo:'Annulla',pause:'Pausa',continue:'Continua',noThanks:'No grazie',backHome:'Torna alla home',gameOver:'Partita finita',playAgain:'Gioca ancora',paused:'In pausa',resume:'Riprendi',restartGame:'Ricomincia',comingSoon:'Prossimamente' },
  ja: { player:'プレイヤー',level:'レベル {level}',stage:'ステージ 1',rewards:'報酬',shop:'ショップ',home:'ホーム',play:'プレイ',profile:'プロフィール',welcomeBack:'おかえりなさい、',dailyReward:'デイリー報酬',claimFree:'無料報酬を受け取ろう！',claim:'受け取る',highestBlock:'最高ブロック',keepMerging:'マージを続けて {goal} を目指そう。',nextGoal:'次の目標：',classicMerge:'クラシックマージ',goalReach:'目標：到達',bestScore:'ベストスコア',playNow:'今すぐプレイ',account:'アカウント',playerProfile:'プレイヤープロフィール',username:'ユーザー名',enterName:'名前を入力',country:'国',language:'言語',searchCountries:'国を検索',searchLanguages:'言語を検索',noCountry:'国が見つかりません',chooseYour:'選択',gameAvatar:'ゲームアバター',styles:'{count} 種類',saveProfile:'プロフィールを保存',cancel:'キャンセル',gems:'ジェム',score:'スコア',best:'ベスト',goal:'目標',next:'次',smash:'破壊',swap:'交換',undo:'戻す',pause:'一時停止',continue:'続ける',noThanks:'結構です',backHome:'ホームへ戻る',gameOver:'ゲームオーバー',playAgain:'もう一度',paused:'一時停止中',resume:'再開',restartGame:'やり直す',comingSoon:'近日公開' },
  ko: { player:'플레이어',level:'레벨 {level}',stage:'스테이지 1',rewards:'보상',shop:'상점',home:'홈',play:'플레이',profile:'프로필',welcomeBack:'다시 오신 것을 환영합니다,',dailyReward:'일일 보상',claimFree:'무료 보상을 받으세요!',claim:'받기',highestBlock:'최고 블록',keepMerging:'계속 합쳐서 {goal}에 도달하세요.',nextGoal:'다음 목표:',classicMerge:'클래식 머지',goalReach:'목표: 도달',bestScore:'최고 점수',playNow:'지금 플레이',account:'계정',playerProfile:'플레이어 프로필',username:'사용자 이름',enterName:'이름 입력',country:'국가',language:'언어',searchCountries:'국가 검색',searchLanguages:'언어 검색',noCountry:'국가를 찾을 수 없음',chooseYour:'선택하세요',gameAvatar:'게임 아바타',styles:'{count}개 스타일',saveProfile:'프로필 저장',cancel:'취소',gems:'보석',score:'점수',best:'최고',goal:'목표',next:'다음',smash:'부수기',swap:'교환',undo:'실행 취소',pause:'일시 정지',continue:'계속',noThanks:'괜찮아요',backHome:'홈으로',gameOver:'게임 오버',playAgain:'다시 플레이',paused:'일시 정지됨',resume:'계속하기',restartGame:'다시 시작',comingSoon:'곧 출시' },
  ms: { player:'Pemain',level:'Tahap {level}',stage:'TAHAP 1',rewards:'Ganjaran',shop:'Kedai',home:'Utama',play:'Main',profile:'Profil',welcomeBack:'Selamat kembali,',dailyReward:'Ganjaran Harian',claimFree:'Tuntut ganjaran percuma anda!',claim:'TUNTUT',highestBlock:'BLOK TERTINGGI',keepMerging:'Terus gabungkan. Capai {goal}.',nextGoal:'Matlamat Seterusnya:',classicMerge:'Gabungan Klasik',goalReach:'Matlamat: Capai',bestScore:'SKOR TERBAIK',playNow:'MAIN SEKARANG',account:'AKAUN',playerProfile:'Profil Pemain',username:'Nama pengguna',enterName:'Masukkan nama anda',country:'Negara',language:'Bahasa',searchCountries:'Cari negara',searchLanguages:'Cari bahasa',noCountry:'Negara tidak ditemui',chooseYour:'PILIH',gameAvatar:'Avatar Permainan',styles:'{count} gaya',saveProfile:'Simpan Profil',cancel:'Batal',gems:'PERMATA',score:'SKOR',best:'TERBAIK',goal:'MATLAMAT',next:'SETERUSNYA',smash:'Hancur',swap:'Tukar',undo:'Buat asal',pause:'Jeda',continue:'Teruskan',noThanks:'Tidak, terima kasih',backHome:'Kembali ke utama',gameOver:'Permainan Tamat',playAgain:'Main lagi',paused:'Dijeda',resume:'Sambung',restartGame:'Mula semula',comingSoon:'Akan datang' },
  pt: { player:'Jogador',level:'Nível {level}',stage:'FASE 1',rewards:'Recompensas',shop:'Loja',home:'Início',play:'Jogar',profile:'Perfil',welcomeBack:'Bem-vindo de volta,',dailyReward:'Recompensa diária',claimFree:'Resgate sua recompensa grátis!',claim:'RESGATAR',highestBlock:'MAIOR BLOCO',keepMerging:'Continue combinando. Alcance {goal}.',nextGoal:'Próximo objetivo:',classicMerge:'Combinação clássica',goalReach:'Objetivo: alcançar',bestScore:'MELHOR PONTUAÇÃO',playNow:'JOGAR AGORA',account:'CONTA',playerProfile:'Perfil do jogador',username:'Nome de usuário',enterName:'Digite seu nome',country:'País',language:'Idioma',searchCountries:'Buscar países',searchLanguages:'Buscar idiomas',noCountry:'País não encontrado',chooseYour:'ESCOLHA SEU',gameAvatar:'Avatar do jogo',styles:'{count} estilos',saveProfile:'Salvar perfil',cancel:'Cancelar',gems:'GEMAS',score:'PONTOS',best:'MELHOR',goal:'OBJETIVO',next:'PRÓXIMO',smash:'Quebrar',swap:'Trocar',undo:'Desfazer',pause:'Pausa',continue:'Continuar',noThanks:'Não, obrigado',backHome:'Voltar ao início',gameOver:'Fim de jogo',playAgain:'Jogar novamente',paused:'Pausado',resume:'Continuar',restartGame:'Reiniciar jogo',comingSoon:'Em breve' },
  ru: { player:'Игрок',level:'Уровень {level}',stage:'ЭТАП 1',rewards:'Награды',shop:'Магазин',home:'Главная',play:'Играть',profile:'Профиль',welcomeBack:'С возвращением,',dailyReward:'Ежедневная награда',claimFree:'Получите бесплатную награду!',claim:'ПОЛУЧИТЬ',highestBlock:'МАКСИМАЛЬНЫЙ БЛОК',keepMerging:'Продолжайте объединять. Цель: {goal}.',nextGoal:'Следующая цель:',classicMerge:'Классическое слияние',goalReach:'Цель: достичь',bestScore:'ЛУЧШИЙ СЧЁТ',playNow:'ИГРАТЬ',account:'АККАУНТ',playerProfile:'Профиль игрока',username:'Имя пользователя',enterName:'Введите имя',country:'Страна',language:'Язык',searchCountries:'Поиск стран',searchLanguages:'Поиск языков',noCountry:'Страна не найдена',chooseYour:'ВЫБЕРИТЕ',gameAvatar:'Аватар игры',styles:'{count} стилей',saveProfile:'Сохранить профиль',cancel:'Отмена',gems:'КРИСТАЛЛЫ',score:'СЧЁТ',best:'ЛУЧШИЙ',goal:'ЦЕЛЬ',next:'ДАЛЕЕ',smash:'Разбить',swap:'Обмен',undo:'Отменить',pause:'Пауза',continue:'Продолжить',noThanks:'Нет, спасибо',backHome:'На главную',gameOver:'Игра окончена',playAgain:'Играть снова',paused:'Пауза',resume:'Продолжить',restartGame:'Начать заново',comingSoon:'Скоро' },
  es: { player:'Jugador',level:'Nivel {level}',stage:'NIVEL 1',rewards:'Premios',shop:'Tienda',home:'Inicio',play:'Jugar',profile:'Perfil',welcomeBack:'Bienvenido de nuevo,',dailyReward:'Recompensa diaria',claimFree:'¡Reclama tu premio gratis!',claim:'RECLAMAR',highestBlock:'BLOQUE MÁS ALTO',keepMerging:'Sigue combinando. Alcanza {goal}.',nextGoal:'Siguiente objetivo:',classicMerge:'Fusión clásica',goalReach:'Objetivo: alcanzar',bestScore:'MEJOR PUNTUACIÓN',playNow:'JUGAR AHORA',account:'CUENTA',playerProfile:'Perfil del jugador',username:'Nombre de usuario',enterName:'Escribe tu nombre',country:'País',language:'Idioma',searchCountries:'Buscar países',searchLanguages:'Buscar idiomas',noCountry:'País no encontrado',chooseYour:'ELIGE TU',gameAvatar:'Avatar del juego',styles:'{count} estilos',saveProfile:'Guardar perfil',cancel:'Cancelar',gems:'GEMAS',score:'PUNTOS',best:'MEJOR',goal:'OBJETIVO',next:'SIGUIENTE',smash:'Romper',swap:'Cambiar',undo:'Deshacer',pause:'Pausa',continue:'Continuar',noThanks:'No, gracias',backHome:'Volver al inicio',gameOver:'Fin del juego',playAgain:'Jugar de nuevo',paused:'En pausa',resume:'Continuar',restartGame:'Reiniciar juego',comingSoon:'Próximamente' },
  sw: { player:'Mchezaji',level:'Kiwango {level}',stage:'HATUA 1',rewards:'Zawadi',shop:'Duka',home:'Nyumbani',play:'Cheza',profile:'Wasifu',welcomeBack:'Karibu tena,',dailyReward:'Zawadi ya Kila Siku',claimFree:'Chukua zawadi yako ya bure!',claim:'CHUKUA',highestBlock:'KIZUIZI CHA JUU',keepMerging:'Endelea kuunganisha. Fikia {goal}.',nextGoal:'Lengo linalofuata:',classicMerge:'Muunganiko wa Kawaida',goalReach:'Lengo: Fikia',bestScore:'ALAMA BORA',playNow:'CHEZA SASA',account:'AKAUNTI',playerProfile:'Wasifu wa Mchezaji',username:'Jina la mtumiaji',enterName:'Weka jina lako',country:'Nchi',language:'Lugha',searchCountries:'Tafuta nchi',searchLanguages:'Tafuta lugha',noCountry:'Nchi haikupatikana',chooseYour:'CHAGUA',gameAvatar:'Avatar ya Mchezo',styles:'Mitindo {count}',saveProfile:'Hifadhi Wasifu',cancel:'Ghairi',gems:'VITO',score:'ALAMA',best:'BORA',goal:'LENGO',next:'INAYOFUATA',smash:'Vunja',swap:'Badilisha',undo:'Tengua',pause:'Sitisha',continue:'Endelea',noThanks:'Hapana, asante',backHome:'Rudi nyumbani',gameOver:'Mchezo Umeisha',playAgain:'Cheza tena',paused:'Imesitishwa',resume:'Endelea',restartGame:'Anza upya',comingSoon:'Inakuja hivi karibuni' },
  th: { player:'ผู้เล่น',level:'เลเวล {level}',stage:'ด่าน 1',rewards:'รางวัล',shop:'ร้านค้า',home:'หน้าหลัก',play:'เล่น',profile:'โปรไฟล์',welcomeBack:'ยินดีต้อนรับกลับ,',dailyReward:'รางวัลรายวัน',claimFree:'รับรางวัลฟรี!',claim:'รับ',highestBlock:'บล็อกสูงสุด',keepMerging:'รวมต่อไป เป้าหมายถัดไป {goal}',nextGoal:'เป้าหมายถัดไป:',classicMerge:'ผสานคลาสสิก',goalReach:'เป้าหมาย: ไปถึง',bestScore:'คะแนนสูงสุด',playNow:'เล่นเลย',account:'บัญชี',playerProfile:'โปรไฟล์ผู้เล่น',username:'ชื่อผู้ใช้',enterName:'ใส่ชื่อของคุณ',country:'ประเทศ',language:'ภาษา',searchCountries:'ค้นหาประเทศ',searchLanguages:'ค้นหาภาษา',noCountry:'ไม่พบประเทศ',chooseYour:'เลือก',gameAvatar:'อวตารเกม',styles:'{count} รูปแบบ',saveProfile:'บันทึกโปรไฟล์',cancel:'ยกเลิก',gems:'อัญมณี',score:'คะแนน',best:'ดีที่สุด',goal:'เป้าหมาย',next:'ถัดไป',smash:'ทุบ',swap:'สลับ',undo:'ย้อนกลับ',pause:'หยุดชั่วคราว',continue:'ดำเนินการต่อ',noThanks:'ไม่ ขอบคุณ',backHome:'กลับหน้าหลัก',gameOver:'จบเกม',playAgain:'เล่นอีกครั้ง',paused:'หยุดชั่วคราว',resume:'เล่นต่อ',restartGame:'เริ่มใหม่',comingSoon:'เร็ว ๆ นี้' },
  tr: { player:'Oyuncu',level:'Seviye {level}',stage:'AŞAMA 1',rewards:'Ödüller',shop:'Mağaza',home:'Ana Sayfa',play:'Oyna',profile:'Profil',welcomeBack:'Tekrar hoş geldin,',dailyReward:'Günlük Ödül',claimFree:'Ücretsiz ödülünü al!',claim:'AL',highestBlock:'EN YÜKSEK BLOK',keepMerging:'Birleştirmeye devam et. {goal} hedefine ulaş.',nextGoal:'Sonraki Hedef:',classicMerge:'Klasik Birleştirme',goalReach:'Hedef: Ulaş',bestScore:'EN İYİ SKOR',playNow:'ŞİMDİ OYNA',account:'HESAP',playerProfile:'Oyuncu Profili',username:'Kullanıcı adı',enterName:'Adını gir',country:'Ülke',language:'Dil',searchCountries:'Ülke ara',searchLanguages:'Dil ara',noCountry:'Ülke bulunamadı',chooseYour:'SEÇ',gameAvatar:'Oyun Avatarı',styles:'{count} stil',saveProfile:'Profili Kaydet',cancel:'İptal',gems:'ELMAS',score:'SKOR',best:'EN İYİ',goal:'HEDEF',next:'SONRAKİ',smash:'Parçala',swap:'Değiştir',undo:'Geri al',pause:'Duraklat',continue:'Devam',noThanks:'Hayır, teşekkürler',backHome:'Ana sayfaya dön',gameOver:'Oyun Bitti',playAgain:'Tekrar oyna',paused:'Duraklatıldı',resume:'Devam et',restartGame:'Yeniden başlat',comingSoon:'Yakında' },
  ur: { player:'کھلاڑی',level:'لیول {level}',stage:'مرحلہ 1',rewards:'انعامات',shop:'دکان',home:'ہوم',play:'کھیلیں',profile:'پروفائل',welcomeBack:'واپسی پر خوش آمدید،',dailyReward:'روزانہ انعام',claimFree:'اپنا مفت انعام حاصل کریں!',claim:'حاصل کریں',highestBlock:'سب سے بڑا بلاک',keepMerging:'ملاتے رہیں۔ اگلا ہدف {goal}۔',nextGoal:'اگلا ہدف:',classicMerge:'کلاسک مرج',goalReach:'ہدف: پہنچیں',bestScore:'بہترین اسکور',playNow:'ابھی کھیلیں',account:'اکاؤنٹ',playerProfile:'کھلاڑی پروفائل',username:'صارف نام',enterName:'اپنا نام لکھیں',country:'ملک',language:'زبان',searchCountries:'ملک تلاش کریں',searchLanguages:'زبان تلاش کریں',noCountry:'ملک نہیں ملا',chooseYour:'منتخب کریں',gameAvatar:'گیم اوتار',styles:'{count} انداز',saveProfile:'پروفائل محفوظ کریں',cancel:'منسوخ',gems:'جواہرات',score:'اسکور',best:'بہترین',goal:'ہدف',next:'اگلا',smash:'توڑیں',swap:'بدلیں',undo:'واپس',pause:'وقفہ',continue:'جاری رکھیں',noThanks:'نہیں شکریہ',backHome:'ہوم پر واپس',gameOver:'کھیل ختم',playAgain:'دوبارہ کھیلیں',paused:'رکا ہوا',resume:'جاری رکھیں',restartGame:'دوبارہ شروع کریں',comingSoon:'جلد آ رہا ہے' },
};

const LANGUAGE_STORAGE_KEY = 'number-merge-language';
const supported = new Set(SUPPORTED_LANGUAGES.map(([code]) => code));
export const isRtlLanguage = (language: LanguageCode) => language === 'ar' || language === 'ur';

function detectLanguage(): LanguageCode {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY)?.toLowerCase();
    if (stored && supported.has(stored as LanguageCode)) return stored as LanguageCode;
  } catch { /* use device language */ }
  const candidates = typeof navigator === 'undefined' ? [] : [...(navigator.languages ?? []), navigator.language];
  for (const candidate of candidates) {
    const base = candidate?.toLowerCase().split('-')[0] as LanguageCode;
    if (supported.has(base)) return base;
  }
  return 'en';
}

type I18nValue = {
  language: LanguageCode;
  direction: 'rtl' | 'ltr';
  setLanguage: (language: LanguageCode) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
  formatNumber: (value: number) => string;
};

const I18nContext = createContext<I18nValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(detectLanguage);
  const direction: 'rtl' | 'ltr' = isRtlLanguage(language) ? 'rtl' : 'ltr';
  const setLanguage = useCallback((next: LanguageCode) => {
    setLanguageState(next);
    try { localStorage.setItem(LANGUAGE_STORAGE_KEY, next); } catch { /* state still works */ }
  }, []);
  const t = useCallback((key: string, values: Record<string, string | number> = {}) => {
    const template = (language === 'en' ? en[key] : packs[language][key]) ?? en[key] ?? key;
    return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
  }, [language]);
  const formatNumber = useCallback((value: number) => new Intl.NumberFormat(language).format(value), [language]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [direction, language]);

  const value = useMemo(() => ({ language, direction, setLanguage, t, formatNumber }), [direction, formatNumber, language, setLanguage, t]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useTranslation(): I18nValue {
  const value = useContext(I18nContext);
  if (!value) throw new Error('useTranslation must be used inside LanguageProvider');
  return value;
}
